# This is your main playbook you will run with:
# ansible-playbook site.yml
# You can kick off everything from this playbook.
# Or, you can create separate playbooks in this directory for specific orchestration events.

---
- name: apply common configuration to all nodes
  hosts: all
  connection: local
  user: root
  tasks:
    - debug:
        msg: "Testing the debug module against host"
    - debug:
        msg: "This is a new commit"
    - debug:
        msg: "this is a commit for the demo"
    - debug:
        msg: "adding some more stuff"
  roles:
    - common

